/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package classic.encription;

/**
 *
 * @author Admin
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ceasar = new javax.swing.JButton();
        simpleText = new javax.swing.JButton();
        Playfair = new javax.swing.JButton();
        vegenere = new javax.swing.JButton();
        swapText = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Classic Cryptions");
        setSize(new java.awt.Dimension(1000, 700));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("Choose an option");

        ceasar.setText("Ceasar Cipher");
        ceasar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ceasarActionPerformed(evt);
            }
        });

        simpleText.setText("Bảng chữ đơn");
        simpleText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpleTextActionPerformed(evt);
            }
        });

        Playfair.setText("Playfair");
        Playfair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayfairActionPerformed(evt);
            }
        });

        vegenere.setText("Vegenere");
        vegenere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vegenereActionPerformed(evt);
            }
        });

        swapText.setText("Chuyển dịch dòng");
        swapText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                swapTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(simpleText, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ceasar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Playfair, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vegenere, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(swapText))))
                .addContainerGap(266, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(ceasar)
                .addGap(18, 18, 18)
                .addComponent(simpleText)
                .addGap(18, 18, 18)
                .addComponent(Playfair)
                .addGap(18, 18, 18)
                .addComponent(vegenere)
                .addGap(18, 18, 18)
                .addComponent(swapText)
                .addContainerGap(194, Short.MAX_VALUE))
        );

        ceasar.getAccessibleContext().setAccessibleName("ceasar");
        simpleText.getAccessibleContext().setAccessibleName("simpleText");
        Playfair.getAccessibleContext().setAccessibleName("playfair");
        vegenere.getAccessibleContext().setAccessibleName("vegenere");
        swapText.getAccessibleContext().setAccessibleName("swapText");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    //Tao cua so window
    private void ceasarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ceasarActionPerformed
        CeasarCipher ceasarCipher = new CeasarCipher();
        ceasarCipher.setVisible(true);
    }//GEN-LAST:event_ceasarActionPerformed

    private void simpleTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpleTextActionPerformed
        simpleText simple = new simpleText();
        simple.setVisible(true);
    }//GEN-LAST:event_simpleTextActionPerformed

    private void PlayfairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayfairActionPerformed
        PlayfairCipher playfair = new PlayfairCipher();
        playfair.setVisible(true);
    }//GEN-LAST:event_PlayfairActionPerformed

    private void vegenereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vegenereActionPerformed
        VegenereCipher vegenere = new VegenereCipher();
        vegenere.setVisible(true);
    }//GEN-LAST:event_vegenereActionPerformed

    private void swapTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_swapTextActionPerformed
        SwapText swap = new SwapText();
        swap.setVisible(true);
    }//GEN-LAST:event_swapTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Playfair;
    public javax.swing.JButton ceasar;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JButton simpleText;
    private javax.swing.JButton swapText;
    private javax.swing.JButton vegenere;
    // End of variables declaration//GEN-END:variables
}
